# Generated by Zero
# import types as per needed, not all imports are shown here
import enum
from msgspec import Struct

from zero import ZeroClient


zero_client = ZeroClient("localhost", 5559)

class RegisteredPlayer(Struct):
    token: str = None
    field : str = None
    is_registered: bool = False



class RpcClient:
    def __init__(self, zero_client: ZeroClient):
        self._zero_client = zero_client

    def register_player(self) -> RegisteredPlayer:
        return self._zero_client.call("register_player", None)
